image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - aaron-bond.better-comments
    - golang.Go
    - esbenp.prettier-vscode
    - asvetliakov.vscode-neovim
    - ms-azuretools.vscode-docker
